from src.database.model.DBEnums import Race
import pandas as pd
class ImportUtil():

    @staticmethod
    def isNa(value):
        if pd.isna(value):
            return None
        return value

    @staticmethod
    def getRaceEnumString(race_str):
        if not race_str:
            return None
        race_mapping = {
            "random": "RANDOM",
            "rd": "RANDOM",
            "undead": "UD",
            "ud": "UD",
            "human": "HU",
            "hu": "HU",
            "night elf": "NE",
            "ne": "NE",
            "orc": "OC",
            "oc": "OC"
            }
        race = race_mapping.get(race_str.lower())
        return race
    
    @staticmethod
    def getRaceNameString(race_enum):
        if not race_enum:
            return None
        race_mapping = {
            "RANDOM": "Random",
            "UD": "Undead",
            "HU": "Human",
            "NE": "Night Elf",
            "OC": "Orc"
            }
        race = race_mapping.get(race_enum.value)
        return race

    @staticmethod  
    def getCountryEnumString(country_name):
        if not country_name:
            return None
        country_mapping = {
            "afghanistan": "AF",
            "albania": "AL",
            "algeria": "DZ",
            "american samoa": "AS",
            "andorra": "AD",
            "angola": "AO",
            "antigua and barbuda": "AG",
            "argentina": "AR",
            "armenia": "AM",
            "australia": "AU",
            "austria": "AT",
            "azerbaijan": "AZ",
            "bahamas": "BS",
            "bahrain": "BH",
            "bangladesh": "BD",
            "barbados": "BB",
            "belarus": "BY",
            "belgium": "BE",
            "belize": "BZ",
            "benin": "BJ",
            "bermuda": "BM",
            "bhutan": "BT",
            "bolivia": "BO",
            "bosnia and herzegovina": "BA",
            "botswana": "BW",
            "brazil": "BR",
            "brunei": "BN",
            "bulgaria": "BG",
            "burkina faso": "BF",
            "burundi": "BI",
            "cabo verde": "CV",
            "cambodia": "KH",
            "cameroon": "CM",
            "canada": "CA",
            "central african republic": "CF",
            "chad": "TD",
            "chile": "CL",
            "china": "CN",
            "colombia": "CO",
            "comoros": "KM",
            "congo": "CG",
            "costa rica": "CR",
            "croatia": "HR",
            "cuba": "CU",
            "cyprus": "CY",
            "czech republic": "CZ",
            "denmark": "DK",
            "djibouti": "DJ",
            "dominica": "DM",
            "dominican republic": "DO",
            "ecuador": "EC",
            "egypt": "EG",
            "el salvador": "SV",
            "equatorial guinea": "GQ",
            "eritrea": "ER",
            "estonia": "EE",
            "eswatini": "SZ",
            "ethiopia": "ET",
            "fiji": "FJ",
            "finland": "FI",
            "france": "FR",
            "gabon": "GA",
            "gambia": "GM",
            "georgia": "GE",
            "germany": "DE",
            "ghana": "GH",
            "greece": "GR",
            "grenada": "GD",
            "guatemala": "GT",
            "guinea": "GN",
            "guinea-bissau": "GW",
            "guyana": "GY",
            "haiti": "HT",
            "honduras": "HN",
            "hungary": "HU",
            "iceland": "IS",
            "india": "IN",
            "indonesia": "ID",
            "iran": "IR",
            "iraq": "IQ",
            "ireland": "IE",
            "israel": "IL",
            "italy": "IT",
            "jamaica": "JM",
            "japan": "JP",
            "jordan": "JO",
            "kazakhstan": "KZ",
            "kenya": "KE",
            "kiribati": "KI",
            "korea, north": "KP",
            "korea, south": "KR",
            "kuwait": "KW",
            "kyrgyzstan": "KG",
            "laos": "LA",
            "latvia": "LV",
            "lebanon": "LB",
            "lesotho": "LS",
            "liberia": "LR",
            "libya": "LY",
            "liechtenstein": "LI",
            "lithuania": "LT",
            "luxembourg": "LU",
            "madagascar": "MG",
            "malawi": "MW",
            "malaysia": "MY",
            "maldives": "MV",
            "mali": "ML",
            "malta": "MT",
            "marshall islands": "MH",
            "mauritania": "MR",
            "mauritius": "MU",
            "mexico": "MX",
            "micronesia": "FM",
            "moldova": "MD",
            "monaco": "MC",
            "mongolia": "MN",
            "montenegro": "ME",
            "morocco": "MA",
            "mozambique": "MZ",
            "myanmar": "MM",
            "namibia": "NA",
            "nauru": "NR",
            "nepal": "NP",
            "netherlands": "NL",
            "new zealand": "NZ",
            "nicaragua": "NI",
            "niger": "NE",
            "nigeria": "NG",
            "north macedonia": "MK",
            "norway": "NO",
            "oman": "OM",
            "pakistan": "PK",
            "palau": "PW",
            "panama": "PA",
            "papua new guinea": "PG",
            "paraguay": "PY",
            "peru": "PE",
            "philippines": "PH",
            "poland": "PL",
            "portugal": "PT",
            "qatar": "QA",
            "romania": "RO",
            "russia": "RU",
            "rwanda": "RW",
            "saint kitts and nevis": "KN",
            "saint lucia": "LC",
            "saint vincent and the grenadines": "VC",
            "samoa": "WS",
            "san marino": "SM",
            "sao tome and principe": "ST",
            "saudi arabia": "SA",
            "senegal": "SN",
            "serbia": "RS",
            "seychelles": "SC",
            "sierra leone": "SL",
            "singapore": "SG",
            "slovakia": "SK",
            "slovenia": "SI",
            "solomon islands": "SB",
            "somalia": "SO",
            "south africa": "ZA",
            "south sudan": "SS",
            "spain": "ES",
            "sri lanka": "LK",
            "sudan": "SD",
            "suriname": "SR",
            "sweden": "SE",
            "switzerland": "CH",
            "syria": "SY",
            "taiwan": "TW",
            "tajikistan": "TJ",
            "tanzania": "TZ",
            "thailand": "TH",
            "timor-leste": "TL",
            "togo": "TG",
            "tonga": "TO",
            "trinidad and tobago": "TT",
            "tunisia": "TN",
            "turkey": "TR",
            "turkmenistan": "TM",
            "tuvalu": "TV",
            "uganda": "UG",
            "ukraine": "UA",
            "united arab emirates": "AE",
            "united kingdom": "GB",
            "united states": "US",
            "uruguay": "UY",
            "uzbekistan": "UZ",
            "vanuatu": "VU",
            "venezuela": "VE",
            "vietnam": "VN",
            "yemen": "YE",
            "zambia": "ZM",
            "zimbabwe": "ZW"
        }

        return country_mapping.get(country_name.lower())
    

    @staticmethod
    def getCountryNameString(iso_code):
        if not iso_code:
            return None
        country_mapping = {
            "AF": "Afghanistan",
            "AL": "Albania",
            "DZ": "Algeria",
            "AS": "American Samoa",
            "AD": "Andorra",
            "AO": "Angola",
            "AG": "Antigua and Barbuda",
            "AR": "Argentina",
            "AM": "Armenia",
            "AU": "Australia",
            "AT": "Austria",
            "AZ": "Azerbaijan",
            "BS": "Bahamas",
            "BH": "Bahrain",
            "BD": "Bangladesh",
            "BB": "Barbados",
            "BY": "Belarus",
            "BE": "Belgium",
            "BZ": "Belize",
            "BJ": "Benin",
            "BM": "Bermuda",
            "BT": "Bhutan",
            "BO": "Bolivia",
            "BA": "Bosnia and Herzegovina",
            "BW": "Botswana",
            "BR": "Brazil",
            "BN": "Brunei",
            "BG": "Bulgaria",
            "BF": "Burkina Faso",
            "BI": "Burundi",
            "CV": "Cabo Verde",
            "KH": "Cambodia",
            "CM": "Cameroon",
            "CA": "Canada",
            "CF": "Central African Republic",
            "TD": "Chad",
            "CL": "Chile",
            "CN": "China",
            "CO": "Colombia",
            "KM": "Comoros",
            "CG": "Congo",
            "CR": "Costa Rica",
            "HR": "Croatia",
            "CU": "Cuba",
            "CY": "Cyprus",
            "CZ": "Czech Republic",
            "DK": "Denmark",
            "DJ": "Djibouti",
            "DM": "Dominica",
            "DO": "Dominican Republic",
            "EC": "Ecuador",
            "EG": "Egypt",
            "SV": "El Salvador",
            "GQ": "Equatorial Guinea",
            "ER": "Eritrea",
            "EE": "Estonia",
            "SZ": "Eswatini",
            "ET": "Ethiopia",
            "FJ": "Fiji",
            "FI": "Finland",
            "FR": "France",
            "GA": "Gabon",
            "GM": "Gambia",
            "GE": "Georgia",
            "DE": "Germany",
            "GH": "Ghana",
            "GR": "Greece",
            "GD": "Grenada",
            "GT": "Guatemala",
            "GN": "Guinea",
            "GW": "Guinea-Bissau",
            "GY": "Guyana",
            "HT": "Haiti",
            "HN": "Honduras",
            "HU": "Hungary",
            "IS": "Iceland",
            "IN": "India",
            "ID": "Indonesia",
            "IR": "Iran",
            "IQ": "Iraq",
            "IE": "Ireland",
            "IL": "Israel",
            "IT": "Italy",
            "JM": "Jamaica",
            "JP": "Japan",
            "JO": "Jordan",
            "KZ": "Kazakhstan",
            "KE": "Kenya",
            "KI": "Kiribati",
            "KP": "Korea, North",
            "KR": "Korea, South",
            "KW": "Kuwait",
            "KG": "Kyrgyzstan",
            "LA": "Laos",
            "LV": "Latvia",
            "LB": "Lebanon",
            "LS": "Lesotho",
            "LR": "Liberia",
            "LY": "Libya",
            "LI": "Liechtenstein",
            "LT": "Lithuania",
            "LU": "Luxembourg",
            "MG": "Madagascar",
            "MW": "Malawi",
            "MY": "Malaysia",
            "MV": "Maldives",
            "ML": "Mali",
            "MT": "Malta",
            "MH": "Marshall Islands",
            "MR": "Mauritania",
            "MU": "Mauritius",
            "MX": "Mexico",
            "FM": "Micronesia",
            "MD": "Moldova",
            "MC": "Monaco",
            "MN": "Mongolia",
            "ME": "Montenegro",
            "MA": "Morocco",
            "MZ": "Mozambique",
            "MM": "Myanmar",
            "NA": "Namibia",
            "NR": "Nauru",
            "NP": "Nepal",
            "NL": "Netherlands",
            "NZ": "New Zealand",
            "NI": "Nicaragua",
            "NE": "Niger",
            "NG": "Nigeria",
            "MK": "North Macedonia",
            "NO": "Norway",
            "OM": "Oman",
            "PK": "Pakistan",
            "PW": "Palau",
            "PA": "Panama",
            "PG": "Papua New Guinea",
            "PY": "Paraguay",
            "PE": "Peru",
            "PH": "Philippines",
            "PL": "Poland",
            "PT": "Portugal",
            "QA": "Qatar",
            "RO": "Romania",
            "RU": "Russia",
            "RW": "Rwanda",
            "KN": "Saint Kitts and Nevis",
            "LC": "Saint Lucia",
            "VC": "Saint Vincent and the Grenadines",
            "WS": "Samoa",
            "SM": "San Marino",
            "ST": "Sao Tome and Principe",
            "SA": "Saudi Arabia",
            "SN": "Senegal",
            "RS": "Serbia",
            "SC": "Seychelles",
            "SL": "Sierra Leone",
            "SG": "Singapore",
            "SK": "Slovakia",
            "SI": "Slovenia",
            "SB": "Solomon Islands",
            "SO": "Somalia",
            "ZA": "South Africa",
            "SS": "South Sudan",
            "ES": "Spain",
            "LK": "Sri Lanka",
            "SD": "Sudan",
            "SR": "Suriname",
            "SE": "Sweden",
            "CH": "Switzerland",
            "SY": "Syria",
            "TW": "Taiwan",
            "TJ": "Tajikistan",
            "TZ": "Tanzania",
            "TH": "Thailand",
            "TL": "Timor-Leste",
            "TG": "Togo",
            "TO": "Tonga",
            "TT": "Trinidad and Tobago",
            "TN": "Tunisia",
            "TR": "Turkey",
            "TM": "Turkmenistan",
            "TV": "Tuvalu",
            "UG": "Uganda",
            "UA": "Ukraine",
            "AE": "United Arab Emirates",
            "GB": "United Kingdom",
            "US": "United States",
            "UY": "Uruguay",
            "UZ": "Uzbekistan",
            "VU": "Vanuatu",
            "VE": "Venezuela",
            "VN": "Vietnam",
            "YE": "Yemen",
            "ZM": "Zambia",
            "ZW": "Zimbabwe"
        }

        return country_mapping.get(iso_code.value)
